### ISSUE TITLE
Allow the user to choose Make/modell car

### ISSUE THREAD

**Issue by Practical-DQ** [2KTinnovations/as24#20]
Through drop down boxes allow the user to choose the car and Modell the want to popluate the graph with

**Comment by Practical-DQ** [comment]
I would like to see this as a bar that Drops in from the top of the Screen. The user makes his choice and the Server goes and gets the Information. When the Chart is filled then the bar dissapears back up. It can be bought back by taking the mouse/finger to the top of the screen

**Comment by Practical-DQ** [comment]
Car Types:
Just let me know if you Need this getting parsed

<optgroup label="----------">
        <option value="51539">9ff</option><option value="16396">Abarth</option><option value="14979">AC</option><option value="16429">ACM</option><option value="16356">Acura</option><option value="16352">Aixam</option><option value="6">Alfa Romeo</option><option value="14">Alpina</option><option value="51545">Amphicar</option><option value="16419">Ariel</option><option value="16427">Artega</option><option value="16431">Aspid</option><option value="8">Aston Martin</option><option value="15643">Austin</option><option value="15644">Autobianchi</option><option value="16400">Bedford</option><option value="16416">Bellier</option><option value="11">Bentley</option><option value="16418">Bolloré</option><option value="16424">Borgward</option><option value="16367">Brilliance</option><option value="15">Bugatti</option><option value="16">Buick</option><option value="16379">BYD</option><option value="17">Cadillac</option><option value="15672">Caravans-Wohnm</option><option value="16407">Casalini</option><option value="16335">Caterham</option><option value="16401">Changhe</option><option value="16357">Chatenet</option><option value="16384">Chery</option><option value="19">Chevrolet</option><option value="20">Chrysler</option><option value="21">Citroen</option><option value="16411">CityEL</option><option value="16406">CMC</option><option value="16380">Corvette</option><option value="51558">Courb</option><option value="16360">Dacia</option><option value="22">Daewoo</option><option value="16333">DAF</option><option value="23">Daihatsu</option><option value="16397">Daimler</option><option value="16434">Dangel</option><option value="16423">De la Chapelle</option><option value="16391">Derways</option><option value="2152">Dodge</option><option value="16339">Donkervoort</option><option value="16383">DR Motor</option><option value="16415">DS</option><option value="51552">Dutton</option><option value="27">Ferrari</option><option value="28">Fiat</option><option value="51543">FISKER</option><option value="51542">Gac Gonow</option><option value="16337">Galloper</option><option value="16386">GAZ</option><option value="16392">Geely</option><option value="16403">GEM</option><option value="51540">GEMBALLA</option><option value="16421">Giotti Victoria</option><option value="2153">GMC</option><option value="16382">Great Wall</option><option value="16409">Grecav</option><option value="51512">Haima</option><option value="51534">Hamann</option><option value="31">Honda</option><option value="15674">HUMMER</option><option value="33">Hyundai</option><option value="16355">Infiniti</option><option value="15629">Innocenti</option><option value="16402">Iso Rivolta</option><option value="35">Isuzu</option><option value="14882">Iveco</option><option value="16387">IZH</option><option value="37">Jaguar</option><option value="38">Jeep</option><option value="16417">Karabag</option><option value="39">Kia</option><option value="50060">KTM</option><option value="40">Lada</option><option value="41">Lamborghini</option><option value="42">Lancia</option><option value="15641">Land Rover</option><option value="16426">LDV</option><option value="43">Lexus</option><option value="16393">Lifan</option><option value="16353">Ligier</option><option value="14890">Lincoln</option><option value="44">Lotus</option><option value="16359">Mahindra</option><option value="16410">Martin Motors</option><option value="45">Maserati</option><option value="16348">Maybach</option><option value="46">Mazda</option><option value="51519">McLaren</option><option value="16399">Melex</option><option value="48">MG</option><option value="16361">Microcar</option><option value="16338">MINI</option><option value="50">Mitsubishi</option><option value="51">Morgan</option><option value="16388">Moskvich</option><option value="51554">MP Lafer</option><option value="52">Nissan</option><option value="53">Oldsmobile</option><option value="15670">Oldtimer</option><option value="16341">Pagani</option><option value="51553">Panther Westwinds</option><option value="55">Peugeot</option><option value="50083">PGO</option><option value="16350">Piaggio</option><option value="56">Pontiac</option><option value="57">Porsche</option><option value="15636">Proton</option><option value="16412">Qoros</option><option value="16425">Qvale</option><option value="16398">Reliant</option><option value="60">Renault</option><option value="61">Rolls-Royce</option><option value="62">Rover</option><option value="51536">Ruf</option><option value="63">Saab</option><option value="16369">Santana</option><option value="16405">Savel</option><option value="64">SEAT</option><option value="65">Skoda</option><option value="15525">smart</option><option value="51538">SpeedArt</option><option value="16377">Spyker</option><option value="66">SsangYong</option><option value="67">Subaru</option><option value="68">Suzuki</option><option value="16395">TagAZ</option><option value="51551">Talbot</option><option value="16404">Tasso</option><option value="16327">Tata</option><option value="51557">Tazzari EV</option><option value="51535">TECHART</option><option value="51520">Tesla</option><option value="16420">Town Life</option><option value="70">Toyota</option><option value="15633">Trabant</option><option value="16326">Trailer-Anhänger</option><option value="2120">Triumph</option><option value="16253">Trucks-Lkw</option><option value="71">TVR</option><option value="16389">UAZ</option><option value="16385">VAZ</option><option value="16422">VEM</option><option value="73">Volvo</option><option value="51514">Vortex</option><option value="16336">Wartburg</option><option value="51513">Westfield</option><option value="16351">Wiesmann</option><option value="16408">Zastava</option><option value="16394">ZAZ</option><option value="16328">Sonstige </option></optgroup>

**Comment by Practical-DQ** [comment]
[as24 Car types.txt](https://github.com/2KTinnovations/as24/files/111034/as24.Car.types.txt)

**Comment by danielkagemann** [comment]
The main problem is that the content is filled during runtime via JavaScript. What you see in browser is the already rendered version. The rendering part us missing when just requesting the website data. 

1. website data is requested
2. script fills the DOM with data and extents it
3. DOM niw has all available data

Running a script to retrieve the data just does 1. So we get an unfinished DOM

DOM = document object model

**Comment by Practical-DQ** [comment]
We have the opportunities later of adding more choice, the concept is ready
