### ISSUE TITLE
Trendline Block

### ISSUE THREAD

**Issue by Practical-DQ** [2KTinnovations/as24#22]
It would be nice if the Points where the trendline are measured would be separeted through a vertical line. essentialy showing a 'block' of either 3 months, 6 months or a year.

Perfect would be if the 'block' could be very sllghtly shaded to Show wether the trend is increasing (red) or decreasing (green)

**Comment by Practical-DQ** [comment]
In Such a bolck Information could be shown as whether the general price has remained stable or volatile

**Comment by danielkagemann** [comment]
not sure about what you mean with block ?

**Comment by Practical-DQ** [comment]
Overloads the graph, not needed.
