### ISSUE TITLE
Format numbers

### ISSUE THREAD

**Issue by danielkagemann** [2KTinnovations/as24#29]
for numbers there should be a thousand separator.

e.g. 1000 to 1.000

**Comment by chriskli** [comment]
So. Also das hier ist ein Kommentar, dass ich die Zahlen gerne entsprechend formatiert und wenn möglich mit der passenden Einheit versehen hätte.

**Comment by danielkagemann** [comment]
Done

**Comment by chriskli** [comment]
mhh.... ich würde einen Trennpunkt (anstatt Komma) bevorzugen. Also 1.000 (für Tausend) anstatt 1,000 (was für mich eher nach 1 aussieht)

**Comment by Practical-DQ** [comment]
Nope! Text is in English, means using the English format, anything else is some sort of eingedeutsched crap. Either all German or all English please

**Comment by chriskli** [comment]
and then you do a copy & paste to put data in excel and the drama is done. At least as24 is a German service with cars from Germany....

**Comment by Practical-DQ** [comment]
Close because works as asked for in context asked for, But new issue with language selection?
