### ISSUE TITLE
Desciption of selected car

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#32]
Only the brand name of the car appears (Ford, Mercedes) but not the selected model. This should show up as well in the graph title.
![image](https://cloud.githubusercontent.com/assets/6191778/12715704/0cb82b88-c8dc-11e5-9655-22ba38a2a388.png)

**Comment by danielkagemann** [comment]
![image](https://cloud.githubusercontent.com/assets/10135014/12728792/c65e8036-c923-11e5-8ef9-d4948843bd25.png)

Done with next version
