### ISSUE TITLE
Graph display in Google Chrome with tool tip issues

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#33]
When looking for a tooltip / mouseover info of one of the cards in the chart, the tooltip is not displayed full in the screen. Instead of this the scrollbar appreas, which disappears again when moving the mouse.

**Comment by danielkagemann** [comment]
please check next version if this problem is fixed. i have adjusted the tooltip box a little bit

**Comment by chriskli** [comment]
tested with latest ZIP, issue remains

**Comment by danielkagemann** [comment]
tooltip replaced by other display strategy
