### ISSUE TITLE
refresh button

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#40]
would be nice to have a refresh button.

**Comment by danielkagemann** [comment]
just click on the view button again to make a refresh.
or do you mean refresh of the data ?

**Comment by chriskli** [comment]
no. it´s the refresh of the view. once data is in memory, no refresh of data is needed for the current session.

**Comment by danielkagemann** [comment]
still open with new UI ?

**Comment by chriskli** [comment]
still open. wenn tested with Ford Focus on Mac: i can change filters and press any button, the amount of cars shown in the graph remains the same

**Comment by chriskli** [comment]
it seems that the filter shows no effect

**Comment by chriskli** [comment]
tested again with Ford Focus: overall amount of cars: 18.001. When deselecting a ZIP code area: clicking again the graph icon, the graph refresh and the number of cars is adapted (18.001 less x cars). adding the same zip code area again, there is no refresh possible. the overall amount of cars is never shown, the filters number of cars remains.

**Comment by danielkagemann** [comment]
there was a huuuuuuge mistake in the filter handling
