### ISSUE TITLE
configure a price area or a direct price

### ISSUE THREAD

**Issue by danielkagemann** [2KTinnovations/as24#44]
![image](https://cloud.githubusercontent.com/assets/10135014/12858758/5bafbbf6-cc52-11e5-8512-bee4104ce5f4.png)

if the price area is huge and a lot of results are displayed it is difficult to find the results within price range.
a) definition of a price filter
b) define price line in chart for better visualisation

**Comment by Practical-DQ** [comment]
We can reduce the data range (and therefor also the Price) by stting a time period.´
See Issue #42

**Comment by Practical-DQ** [comment]
Linked to issue #16

**Comment by danielkagemann** [comment]
![bildschirmfoto 2016-02-20 um 23 42 25](https://cloud.githubusercontent.com/assets/10135014/13199651/aaae9ba2-d82b-11e5-8f7d-a5fb26464f86.png)
Price can be defined. the min/max can is automatically adjusted. 
The area is highlighted and all the boxes where the median is out of this range is dimmed.
