### ISSUE TITLE
when choosing a brand and select all: no data retrieval can be started

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#48]
when selecting only the car brand in the model box "alle" is preselected . but to is not possible to start with data retrieval.
Instead of "alle" another term should be there that obligates the user to select a model. eg: select a model
Bildschirmfoto 2016-02-07 um 19.11.16.png
<img width="1212" alt="bildschirmfoto 2016-02-07 um 19 11 16" src="https://cloud.githubusercontent.com/assets/6191778/12874178/01faf08e-cdcf-11e5-9b66-9baf5c7fb347.png">

**Comment by danielkagemann** [comment]
should be no longer an issue due to UI redesign
