### ISSUE TITLE
no data are retrieve, but records are expected

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#49]
as the screenshot shows, there should be some data. Is there a way to do a refresh?
<img width="858" alt="bildschirmfoto 2016-02-07 um 19 53 27" src="https://cloud.githubusercontent.com/assets/6191778/12874481/03f1a4a4-cdd5-11e5-98a2-825f6674df86.png">

**Comment by danielkagemann** [comment]
should work now.
