### ISSUE TITLE
what means range in the screenshot example?

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#50]
the range is the same value as the median. Is this correct?
<img width="281" alt="bildschirmfoto 2016-02-07 um 19 50 55" src="https://cloud.githubusercontent.com/assets/6191778/12874540/f768c5d6-cdd5-11e5-96e5-b3db74ec08c8.png">

**Comment by danielkagemann** [comment]
![bildschirmfoto 2016-02-10 um 22 54 35](https://cloud.githubusercontent.com/assets/10135014/12963148/4bd9d25c-d049-11e5-9960-8b2b6b5bde55.png)

Texts revised:

Minimum is lowest price
maximum is highest price
range is majority between
median is well, median
