### ISSUE TITLE
Auto deploy of new as24 version 

### ISSUE THREAD

**Issue by danielkagemann** [2KTinnovations/as24#51]
Automated archives when new commut is done. Maybe a test version on 2k1t.net

**Comment by Practical-DQ** [comment]
please explain for the stupid people (me!)

**Comment by danielkagemann** [comment]
At the moment each version must be manually put into slack or elsewhere. This could be done automatically on each commit. 

Thinking of a continuous integration (build) server.
This could be any computer but makes more sense when my mac at home will do this job.
