### ISSUE TITLE
Auf der landing page fehlt eine Tilde im Titel

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#53]
Bei Welcome, Herzliche Willkommen und Bienvenue fehlt die Tilde (das Trennzeichen zwischen den letzten beiden Sprachen.

![image](https://cloud.githubusercontent.com/assets/6191778/12922201/b848a3a4-cf50-11e5-9416-c5fe85462fba.png)

**Comment by danielkagemann** [comment]
done in next version
