### ISSUE TITLE
in the select box of the car Audi is offered but no model available

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#57]
when trying to look for Audi, there is no model selection offered

Bildschirmfoto 2016-02-10 um 08.55.28.png
<img width="1269" alt="bildschirmfoto 2016-02-10 um 08 55 28" src="https://cloud.githubusercontent.com/assets/6191778/12941611/7f6aea18-cfd4-11e5-9239-dce56df11138.png">

**Comment by danielkagemann** [comment]
done
