### ISSUE TITLE
Better Use of space in Graph?

### ISSUE THREAD

**Issue by Practical-DQ** [2KTinnovations/as24#59]
If we bring out the trendline filter to the top right Corner, Then have the legend undernath that ontop of the graph. This would allow the y axis of the graph a further 2-3 cms in height.

**Comment by danielkagemann** [comment]
![bildschirmfoto 2016-02-11 um 23 50 27](https://cloud.githubusercontent.com/assets/10135014/12993425/50423538-d11a-11e5-9db9-2097de1b9c47.png)
