### ISSUE TITLE
when setting and deleting filters, not possible to play with data

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#60]
when setting and deleting filters, it is not possible to play around with the data. Switching from graph modus to table modus is possible, but not to geo modus. the geo table is not going to be displayed.
Taking a look in the terminal, there are no changes anyway, to maybe the server crashed?

**Comment by danielkagemann** [comment]
there was an error in the geo plz handling.
division by zero in km band handling.
kilometre still losing some cars.

**Comment by danielkagemann** [comment]
should work now
