### ISSUE TITLE
Zahlen in Graph ohne Legende und unverständlich

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#71]
was bedeuten diese Zahlen? Sie sind auch nicht wirklich leserlich.
<img width="1276" alt="bildschirmfoto 2016-02-22 um 09 45 28" src="https://cloud.githubusercontent.com/assets/6191778/13213462/54371136-d949-11e5-9d77-f7700663f7fa.png">

**Comment by danielkagemann** [comment]
Das ist ein erster Entwurf für Stability & loss. Diente lediglich zur Veranschaulichung. Sieht noch total bescheiden aus.

**Comment by danielkagemann** [comment]
Besser mit neuer Version
