### ISSUE TITLE
Zahlen unleserlich in Geodata Modus

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#72]
Die Trendlinse sind nicht schlecht. Im Mouseover sind aber die hinterlegten Zahlen unleserlich.
<img width="682" alt="bildschirmfoto 2016-02-22 um 09 55 32" src="https://cloud.githubusercontent.com/assets/6191778/13213673/d342369e-d94a-11e5-9087-e6ae4a23279d.png">

**Comment by danielkagemann** [comment]
tooltip disabled. no real benefit.
